{% set version = "0.2.7" %}

package:
  name: ruamel.yaml.clib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/ruamel.yaml.clib/ruamel.yaml.clib-{{ version }}.tar.gz
  sha256: 1f08fd5a2bea9c4180db71678e850b995d2a5f4537be0e94557668cf0f5f9497

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  downstreams:
    - ruamel.yaml
  commands:
    - test -f ${SP_DIR}/_ruamel_yaml.*${SHLIB_EXT}  # [not win]
    - if not exist %SP_DIR%\_ruamel_yaml.*%SHLIB_EXT% exit 1  # [win]

about:
  home: https://sourceforge.net/projects/ruamel-yaml-clib/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: C version of reader, parser and emitter for ruamel.yaml derived from libyaml

extra:
  recipe-maintainers:
    - mbargull
    - ocefpaf
